- name: "Local compilation"
  hosts: all
  connection: local
  vars_files:
    - vars/default.yml
    - [~/.personal_ansible_vm.yml, vars/empty.yml]
    - [../personal.yml, vars/empty.yml]
  roles:
    - create_shop_config
    - build_backend


- name: "Deploy"
  hosts: all
  gather_facts: no
  remote_user: www-data
  vars_files:
    - vars/default.yml
    - [~/.personal_ansible_vm.yml, vars/empty.yml]
    - [../personal.yml, vars/empty.yml]
  roles:
    - deploy
    - fixup
#    - slack_notification
