#
# roles/build_backend/tasks/main.yml
#
---
- name: Composer install
  local_action:
    module: shell
    _raw_params: composer install --no-dev
    args:
      chdir: "{{ build_root_path }}/oxideshop/"
  environment:
    COMPOSER_HOME: "{{ lookup('env', 'COMPOSER_HOME') }}"
  run_once: true
  become: yes
