version: '3.5'

services:
  php:
    build:
      context: ./docker/php
    depends_on:
      - db
    restart: unless-stopped
    #increase shop performance but loose installed packages after restart
    #tmpfs: /var/www/oxideshop/vendor:exec,mode=777
    volumes:
      - ./docker/php/install.sh:/tmp/install.sh
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/msmtprc:/etc/msmtprc
      - ./oxideshop/:/var/www/oxideshop:cached
      - ./tmp:/var/www/tmp:delegated
      - ./scripts/:/scripts:cached
      - composer:/var/composer_cache
      - user:/home/root
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: db
      MYSQL_PORT: ${MYSQL_PORT}
      DOMAIN: ${DOMAIN}
      OXID_PORT: ${OXID_PORT}
      SSL_OXID_PORT: ${SSL_OXID_PORT}
      PHP_IDE_CONFIG: "serverName=${DOMAIN}"
      CONTAINER_UID: ${CONTAINER_UID}
      COMPOSER_CACHE_DIR: "/var/composer_cache"
    working_dir: /var/www/oxideshop
    ports:
      - ${OXID_PORT}:80
      - ${SSL_OXID_PORT}:443
    networks:
      - dev
#   user: www-data
    command: ["/bin/bash", "/tmp/install.sh"]

  db:
    build:
      context: ./docker/db
      args:
        DB_IMAGE: ${DB_IMAGE}
    restart: unless-stopped
#make the db fast but loose all data after restart
#    tmpfs: /var/lib/mysql
    volumes:
      - db:/var/lib/mysql
      - ./docker/db-dump/initial-data.sql:/docker-entrypoint-initdb.d/initial-data.sql:cached
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Europe/Berlin
    ports:
      - "${DB_PORT}:${MYSQL_PORT:-3306}"
    networks:
      - dev

  mailhog:
    image: mailhog/mailhog
    ports:
      - "${MAILHOG_UI_PORT}:8025"
    networks:
      - dev

  selenium:
    image: selenium/standalone-chrome-debug:3.141.59-lithium
    volumes:
      - /dev/shm:/dev/shm
    environment:
      VNC_NO_PASSWORD: 1
    ports:
      - "${SELENIUM_PORT:-4444}:4444"
      - "5901:5901"
    networks:
      - dev

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - ${ADMINER_HOST_PORT:-8080}:8080
    networks:
      - dev

networks:
  dev:
volumes:
  composer:
    driver: local
  user:
    driver: local
  db:
    driver: local