- name: (Deprecated. Should be updated to use deliver role.) Initialize the deploy root and gather facts
  deploy_helper: path={{ webroot_path }} state=present

- name: Create the current release directory
  file: path={{ deploy_helper.new_release_path }} state=directory

- name: Add an unfinished file, to allow cleanup on successful finalize
  file: path={{ deploy_helper.new_release_path }}/{{ deploy_helper.unfinished_filename }} state=touch

- name: Synchronize configuration files to target
  synchronize: src="{{ build_root_path }}/configurations" dest={{ deploy_helper.shared_path }} recursive=yes

- name: Synchronize resource files to target
  synchronize: src="{{ build_root_path }}/{{ item.path }}" dest={{ deploy_helper.shared_path }} recursive=yes
  with_items: "{{ oxid.shared_directories }}"

- name: Synchronize shop source files to target
  synchronize: src="{{ build_root_path }}/" dest="{{ deploy_helper.new_release_path }}/" delete=yes recursive=yes

- name: Ensure symlinked directories exists
  file: path='{{ deploy_helper.shared_path }}/{{ item.src }}' state=directory mode=0777
  with_items: "{{ oxid.shared_directories }}"

- name: Ensure symlinked files exists
  file: path='{{ deploy_helper.shared_path }}/{{ item.src }}' state=file mode=0777
  with_items: "{{ oxid.shared_files }}"
  tags:
    - deploy
    - release
    - symlink

- name: Remove folders which are symlinked
  file: path='{{ deploy_helper.new_release_path }}/{{ item.path }}'
        state=absent
  with_items: "{{ oxid.shared_directories }}"

- name: Add symlinks from the new release to the shared folder
  file: path='{{ deploy_helper.new_release_path }}/{{ item.path }}'
        src='{{ deploy_helper.shared_path }}/{{ item.src }}'
        state=link
        force=yes
  with_items:
    - "{{ oxid.shared_directories }}"
    - "{{ oxid.shared_files }}"

- name: Finalize the deploy, removing the unfinished file and switching the symlink
  deploy_helper: path={{ webroot_path }} release="{{ deploy_helper.new_release }}" state=finalize current_path={{ oxid.current_path_name }}
