---
# Commit prev
- name: Git stage mailhog systemd file
  command:
    cmd: git add systemd/system/mailhog.service systemd/system/multi-user.target.wants/mailhog.service
    chdir: /etc/
  when:
    - use_etckeeper
    - "ansible_service_mgr == 'systemd'"
  become: yes

# Commit prev
- name: Git stage mailhog unit file
  command:
    cmd: git add /etc/init.d/mailhog
    chdir: /etc/
  when:
    - use_etckeeper
    - "ansible_service_mgr != 'systemd'"
  become: yes

- name: Configure php ini files
  ini_file:
    path: "{{ item }}"
    section: mail function
    option: sendmail_path
    value: "{{ mailhog_install_dir }}/mhsendmail"
    backup: yes
  with_items: "{{ php_config_files }}"

- name: Stage configured php ini files
  command:
    cmd: "git add {{ item }}"
    chdir: /etc/
  with_items: "{{ php_config_files }}"

- name: Test if apache is already configured
  shell: grep "ProxyPass /mailhog/"  "{{apache_config_file}}"
  register: grep_output
  ignore_errors: yes

- name: Add apache proxy for mailhog
  shell: |
    sed -i 's/<\/VirtualHost>/        ProxyPass \/mailhog\/ http:\/\/localhost:8025\/\
              ProxyPassReverse \/mailhog\/ http:\/\/localhost:8025\/\
              <\/VirtualHost>/g'  "{{apache_config_file}}"
  when:
    grep_output.failed

- name: Git stage apache changes
  command:
    cmd: git add  "{{apache_config_file}}"
    chdir: /etc/
  when: use_etckeeper

- name: Activate proxy http module
  apache2_module:
    state: present
    name: proxy_http

- name: Git stage apache changes
  command:
    cmd: git add apache2/mods-enabled/
    chdir: /etc/
  when: use_etckeeper

- name: Check if we need to commit
  shell: git status | grep "Changes to be committed"
  args:
    chdir: /etc/
  register: git_stage
  ignore_errors: yes
  when: use_etckeeper

- name: Commit stages files
  command:
    cmd: git commit -m 'Mailhog installation'
    chdir: /etc/
  when:
    - use_etckeeper
    - not git_stage.failed
  become: yes

