---
shop_domain: "pp.oxidps.de"
oxid:
  shop_url: "https://{{ shop_domain }}/"
  shop_path: "{{ deployment_root }}/current/oxideshop/source"
  shop_tmp_path: "{{ deployment_root }}/current/oxideshop/source/tmp"
  ssl_shop_url: "https://{{ shop_domain }}/"
  admin_ssl_url: "https://{{ shop_domain }}/admin"
  environment_name: "{{ env }}"
  shared_directories:
  - { path: "oxideshop/source/out/pictures",  src: "out/pictures" }
  - { path: "oxideshop/source/out/downloads",  src: "out/downloads" }
  - { path: "oxideshop/source/out/media", src: "out/media" }
  - { path: "oxideshop/source/log",  src: "log" }
  - { path: "oxideshop/source/tmp",  src: "tmp" }
  - { path: "oxideshop/source/cache",  src: "cache" }
mysql:
  host: localhost
  database: oxid
  user: oxid
  password: oxid
