---
# Mailhog section
# Parameters used when creating new Certbot certs.
ansible_service_mgr: systemd
use_etckeeper: true
apache_config_file: /path/to/etc/apache2/sites-available/your_vhost.conf

# Certbot section
# We want to renew our certificate
certbot_auto_renew: true
certbot_auto_renew_hour: "4"
certbot_auto_renew_minute: "42"
# set webroot in renew options
certbot_auto_renew_options: "--webroot --webroot-path {{ oxid.shop_path }} --quiet --no-self-upgrade"

# Creation of certificate on first installation
certbot_create_if_missing: true

# we won't use standalone method, but this variable should be set
certbot_create_method: standalone
certbot_admin_email: some@email.local
certbot_certs:
- domains:
    - "{{ shop_domain }}"

# Set webroot option
certbot_create_command: >-
  {{ certbot_script }} certonly --noninteractive --agree-tos
  --email {{ cert_item.email | default(certbot_admin_email) }}
  --webroot --webroot-path  {{ oxid.shop_path }}
  -d {{ cert_item.domains | join(',') }}

# Because we are using webroot, we don't need to stop anything
certbot_create_standalone_stop_services: []
