---
- name: Install xDebug
  become: yes
  apt: pkg="php{{ php.version }}-xdebug" state=latest

- name: Capture outgoing IP address
  shell: route | tail -n 1 | awk -F ' ' '{print $1}' | sed 's/\.0$/\.1/g'
  become: yes
  register: xdebug_ip_address

- name: Place xdebug configuration
  template: src=xdebug.ini dest=/etc/php/{{ php.version }}/mods-available/xdebug.ini
  become: yes
  notify: restart apache

- name: Enable xdebug in terminal
  shell: |
    sudo sh -c "echo '#! /bin/bash
    export XDEBUG_CONFIG=\"idekey=PHPSTORM\" &&
    export PHP_IDE_CONFIG=\"serverName=getnow.local\" &&
    php \"\$@\"' > /usr/local/bin/phpd; chmod +x /usr/local/bin/phpd"
  args:
    executable: /bin/bash
  become: yes
