---
- name: Activate OXID Module Configuration Im-/Exporter
  command: vendor/bin/oxid module:activate oxps/modulesconfig
  args:
    chdir: "{{ target_vendor_path }}/../"
  run_once: true

- name: Import environment specific configuration
  command: "vendor/bin/oxid config:import --env={{ oxid.environment_name }}"
  args:
    chdir: "{{ target_vendor_path }}/../"
  run_once: true
